import React, { useMemo, useRef, useState } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { AdaptiveDpr, ContactShadows, Environment, Float, MeshTransmissionMaterial, RoundedBox, Sparkles, useCursor } from '@react-three/drei';
import { Bloom, DepthOfField, EffectComposer, N8AO } from '@react-three/postprocessing';
import * as THREE from 'three';

const GLASS = { transmission: .985, thickness: .42, roughness: .045, ior: 1.47, chromaticAberration: .018, anisotropy: .18, distortion: .035, distortionScale: .12, temporalDistortion: .03, color: '#eafff0' };
function useLatheProfile(points) { return useMemo(() => new THREE.LatheGeometry(points.map(([r, y]) => new THREE.Vector2(r, y)), 160), [points]); }
function Capsule({ position, rotation = [0,0,0], green = true, scale = 1, speed = 1 }) { const ref=useRef(); useFrame((s)=>{if(ref.current){const t=s.clock.elapsedTime*speed;ref.current.position.y=position[1]+Math.sin(t+position[0])*.11;ref.current.rotation.x+=.003*speed;ref.current.rotation.z=rotation[2]+Math.sin(t)*.15}}); const color=green?'#16aa5c':'#fcfffd'; return <group ref={ref} position={position} rotation={rotation} scale={scale}><mesh castShadow><capsuleGeometry args={[.155,.43,24,48]}/><meshPhysicalMaterial color={color} roughness={.16} clearcoat={1} clearcoatRoughness={.1}/></mesh><mesh rotation={[0,0,Math.PI/2]}><torusGeometry args={[.158,.007,10,48]}/><meshStandardMaterial color={green?'#087c40':'#b9d5c3'} metalness={.15} roughness={.22}/></mesh></group>; }
function Label(){return <group position={[0,.03,-.854]}><RoundedBox args={[1.19,.69,.018]} radius={.055} smoothness={8}><meshPhysicalMaterial color="#fbfffc" roughness={.28} clearcoat={.65}/></RoundedBox><mesh position={[0,.19,.016]}><planeGeometry args={[.72,.045]}/><meshBasicMaterial color="#188d50"/></mesh><mesh position={[0,.03,.016]}><planeGeometry args={[.52,.025]}/><meshBasicMaterial color="#9ab7a5"/></mesh><mesh position={[0,-.08,.016]}><planeGeometry args={[.66,.018]}/><meshBasicMaterial color="#c4d7cc"/></mesh><mesh position={[0,-.16,.016]}><planeGeometry args={[.47,.018]}/><meshBasicMaterial color="#c4d7cc"/></mesh></group>}
function PremiumBottle(){const group=useRef();const[hovered,setHovered]=useState(false);useCursor(hovered);const body=useLatheProfile([[.63,-1.28],[.74,-1.22],[.82,-1.09],[.84,-.74],[.84,.62],[.8,.86],[.69,1.03],[.48,1.13],[.43,1.22],[.43,1.44]]);const cap=useLatheProfile([[.46,1.42],[.51,1.47],[.51,1.72],[.48,1.79],[.41,1.82],[.39,1.76],[.39,1.47]]);useFrame((s)=>{if(group.current){const t=s.clock.elapsedTime;group.current.position.y=Math.sin(t*.7)*.1;group.current.rotation.y=Math.sin(t*.38)*.087+s.pointer.x*.16;group.current.rotation.x=s.pointer.y*.1}});return <group ref={group} onPointerOver={()=>setHovered(true)} onPointerOut={()=>setHovered(false)}><mesh geometry={body} castShadow><MeshTransmissionMaterial {...GLASS}/></mesh><mesh position={[0,0,-.845]}><planeGeometry args={[1.12,.86]}/><meshPhysicalMaterial color="#fbfffc" roughness={.35} transparent opacity={.42}/></mesh><Label/><mesh geometry={cap} castShadow><meshPhysicalMaterial color="#f8fffa" metalness={.72} roughness={.18} clearcoat={1}/></mesh>{[1.51,1.59,1.67,1.75].map(y=><mesh key={y} position={[0,y,0]}><torusGeometry args={[.512,.012,8,96]}/><meshStandardMaterial color="#b9d4c4" metalness={.85} roughness={.24}/></mesh>)}<group position={[0,-.05,.05]} rotation={[.2,-.2,.25]}><Capsule position={[-.27,.21,.35]} scale={.76} speed={.55}/><Capsule position={[.24,-.22,.38]} green={false} scale={.72} speed={.7}/><Capsule position={[.03,.45,-.08]} scale={.63} speed={.5}/></group></group>}
function Tablet({position,scale=1,speed=1}){const ref=useRef();useFrame(s=>{if(ref.current){ref.current.rotation.x=s.clock.elapsedTime*.22*speed;ref.current.position.y=position[1]+Math.sin(s.clock.elapsedTime*speed+position[0])*.1}});return <mesh ref={ref} position={position} scale={scale} castShadow><sphereGeometry args={[.205,48,32]}/><meshPhysicalMaterial color="#fafffc" roughness={.15} clearcoat={1}/></mesh>}
function Rings({reducedMotion}){const primary=useRef(),secondary=useRef();useFrame(s=>{if(reducedMotion)return;const t=s.clock.elapsedTime;if(primary.current){primary.current.scale.setScalar(1+Math.sin(t*1.25)*.06);primary.current.rotation.z=t*.12}if(secondary.current)secondary.current.scale.setScalar(1+Math.sin(t+1)*.1)});return <group rotation={[-Math.PI/2,0,0]} position={[0,-1.53,0]}><mesh ref={primary}><torusGeometry args={[1.7,.016,12,128]}/><meshBasicMaterial color="#52e18e" transparent opacity={.68}/></mesh><mesh ref={secondary}><torusGeometry args={[2.12,.008,8,128]}/><meshBasicMaterial color="#a1f5c2" transparent opacity={.5}/></mesh><mesh><circleGeometry args={[1.56,96]}/><meshBasicMaterial color="#4ee189" transparent opacity={.13}/></mesh></group>}
function Studio({reducedMotion}){const items=useMemo(()=>[[-1.75,.58,.12,.8,true],[1.62,.72,.12,.7,false],[1.54,-.48,.12,.56,true],[-1.3,-.64,.1,.58,false]],[]);return <><ambientLight intensity={.72}/><directionalLight position={[-3.5,5,5]} intensity={3.4} color="#fffdf8" castShadow/><pointLight position={[3,2,2]} intensity={18} color="#eaffef" distance={7}/><pointLight position={[-3,.3,-1]} intensity={13} color="#69ec9d" distance={5}/><spotLight position={[0,4,-3]} intensity={20} angle={.48} penumbra={1} color="#d4ffe2"/><Float speed={reducedMotion?0:1.15} rotationIntensity={0} floatIntensity={reducedMotion?0:.2}><PremiumBottle/></Float>{items.map(([x,y,z,s,g],i)=><Capsule key={i} position={[x,y,z]} scale={s} green={g} speed={.42+i*.14} rotation={[i*.4,i*.8,i*.25]}/>) }<Tablet position={[-1.44,1.45,-.3]} scale={.84} speed={.7}/><Tablet position={[1.76,-.1,-.32]} scale={.65} speed={.55}/><Rings reducedMotion={reducedMotion}/><mesh position={[0,.1,-1.8]}><coneGeometry args={[2.25,4.2,64,1,true]}/><meshBasicMaterial color="#83edaf" transparent opacity={.045} depthWrite={false} side={THREE.DoubleSide}/></mesh><Sparkles count={reducedMotion?12:55} scale={[5,4.4,2.3]} size={2} speed={.25} color="#74eda4"/><ContactShadows position={[0,-1.54,0]} opacity={.45} scale={5.3} blur={2.2} far={3.2}/><Environment preset="studio" environmentIntensity={1.45}/><EffectComposer multisampling={0}><N8AO aoRadius={1.2} intensity={1.4}/><Bloom mipmapBlur luminanceThreshold={.65} intensity={.58} radius={.68}/><DepthOfField focusDistance={.02} focalLength={.035} bokehScale={1.7} height={480}/></EffectComposer></>}
export default function PharmaceuticalScene({reducedMotion}){return <Canvas dpr={[1,1.75]} shadows camera={{position:[0,.15,5.55],fov:38}} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}}><AdaptiveDpr pixelated/><Studio reducedMotion={reducedMotion}/></Canvas>}
